Update update-version-abstractions.yml

diff --git a/.github/workflows/update-version-abstractions.yml b/.github/workflows/update-version-abstractions.yml
--- a/.github/workflows/update-version-abstractions.yml
+++ b/.github/workflows/update-version-abstractions.yml
@@ -152,13 +152,13 @@ jobs:
         id: set-branch-name
         run: |
           echo "value=bot/${{ steps.set-project-name.outputs.value }}/update-version" >> $GITHUB_OUTPUT
-      - name: Reset branch
-        run: |
-          BRANCH="${{ steps.set-branch-name.outputs.value }}"
-          is_branch_exists_origin=$(git ls-remote --heads origin $BRANCH | grep -q "refs/heads/$BRANCH" && echo true || echo false)
-          if [[ "$is_branch_exists_origin" == "true" ]]; then
-            git push origin --delete $BRANCH || { echo "Failed to delete branch $BRANCH on origin."; exit 1; }
-          fi
+      # - name: Reset branch
+      #   run: |
+      #     BRANCH="${{ steps.set-branch-name.outputs.value }}"
+      #     is_branch_exists_origin=$(git ls-remote --heads origin $BRANCH | grep -q "refs/heads/$BRANCH" && echo true || echo false)
+      #     if [[ "$is_branch_exists_origin" == "true" ]]; then
+      #       git push origin --delete $BRANCH || { echo "Failed to delete branch $BRANCH on origin."; exit 1; }
+      #     fi
       - uses: ./.github/actions/setup-git
         with:
           branch: ${{ steps.set-branch-name.outputs.value }}
